import type { CountryData } from '@conflict-game/shared-types';

export const SEED_COUNTRIES: CountryData[] = [
  // ─────────────────────────────────────────────────────────────────────────────
  // 1. United States
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'US',
    name: 'United States',
    capital: 'Washington D.C.',
    region: 'North America',
    subregion: 'Northern America',
    latitude: 38.8951,
    longitude: -77.0364,
    area: 9833520,
    population: 331900000,
    flag: '🇺🇸',
    startingState: {
      code: 'US',
      economy: {
        gdp: 25000,
        gdpGrowth: 2.1,
        budget: 50,
        taxRate: 0.25,
        tradeBalance: -800,
        debtToGdp: 1.23,
        inflation: 3.5,
        sanctionResilience: 85,
        sanctionEvasion: 20,
      },
      military: {
        army: 1400000,
        navy: 490,
        airForce: 5200,
        nuclearWeapons: 5500,
        defenseBudget: 886,
        techLevel: 9,
      },
      resources: { oil: 85, gas: 90, metals: 70, rareEarth: 15, food: 95, water: 85 },
      stability: 65,
      approval: 45,
      techLevel: 9,
      diplomaticInfluence: 95,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 2. China
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'CN',
    name: 'China',
    capital: 'Beijing',
    region: 'Asia',
    subregion: 'Eastern Asia',
    latitude: 39.9042,
    longitude: 116.4074,
    area: 9596961,
    population: 1412000000,
    flag: '🇨🇳',
    startingState: {
      code: 'CN',
      economy: {
        gdp: 18000,
        gdpGrowth: 5.2,
        budget: 40,
        taxRate: 0.22,
        tradeBalance: 680,
        debtToGdp: 0.77,
        inflation: 2.0,
        sanctionResilience: 80,
        sanctionEvasion: 45,
      },
      military: {
        army: 2035000,
        navy: 370,
        airForce: 3200,
        nuclearWeapons: 350,
        defenseBudget: 293,
        techLevel: 7,
      },
      resources: { oil: 35, gas: 30, metals: 80, rareEarth: 95, food: 75, water: 55 },
      stability: 72,
      approval: 70,
      techLevel: 7,
      diplomaticInfluence: 80,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 3. Russia
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'RU',
    name: 'Russia',
    capital: 'Moscow',
    region: 'Europe',
    subregion: 'Eastern Europe',
    latitude: 55.7558,
    longitude: 37.6173,
    area: 17098242,
    population: 144100000,
    flag: '🇷🇺',
    startingState: {
      code: 'RU',
      economy: {
        gdp: 2240,
        gdpGrowth: -2.1,
        budget: 18,
        taxRate: 0.20,
        tradeBalance: 150,
        debtToGdp: 0.17,
        inflation: 12.0,
        sanctionResilience: 65,
        sanctionEvasion: 60,
      },
      military: {
        army: 1150000,
        navy: 310,
        airForce: 4100,
        nuclearWeapons: 6250,
        defenseBudget: 86,
        techLevel: 7,
      },
      resources: { oil: 95, gas: 95, metals: 85, rareEarth: 20, food: 60, water: 90 },
      stability: 55,
      approval: 60,
      techLevel: 6,
      diplomaticInfluence: 55,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 4. India
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'IN',
    name: 'India',
    capital: 'New Delhi',
    region: 'Asia',
    subregion: 'Southern Asia',
    latitude: 28.6139,
    longitude: 77.209,
    area: 3287263,
    population: 1408000000,
    flag: '🇮🇳',
    startingState: {
      code: 'IN',
      economy: {
        gdp: 3730,
        gdpGrowth: 6.8,
        budget: 22,
        taxRate: 0.18,
        tradeBalance: -270,
        debtToGdp: 0.83,
        inflation: 5.7,
        sanctionResilience: 70,
        sanctionEvasion: 40,
      },
      military: {
        army: 1455000,
        navy: 150,
        airForce: 2100,
        nuclearWeapons: 164,
        defenseBudget: 81,
        techLevel: 5,
      },
      resources: { oil: 15, gas: 10, metals: 55, rareEarth: 10, food: 80, water: 50 },
      stability: 58,
      approval: 55,
      techLevel: 5,
      diplomaticInfluence: 50,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 5. United Kingdom
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'GB',
    name: 'United Kingdom',
    capital: 'London',
    region: 'Europe',
    subregion: 'Northern Europe',
    latitude: 51.5074,
    longitude: -0.1278,
    area: 243610,
    population: 67330000,
    flag: '🇬🇧',
    startingState: {
      code: 'GB',
      economy: {
        gdp: 3070,
        gdpGrowth: 1.4,
        budget: 35,
        taxRate: 0.27,
        tradeBalance: -220,
        debtToGdp: 1.01,
        inflation: 6.8,
        sanctionResilience: 60,
        sanctionEvasion: 15,
      },
      military: {
        army: 149000,
        navy: 75,
        airForce: 800,
        nuclearWeapons: 225,
        defenseBudget: 68,
        techLevel: 8,
      },
      resources: { oil: 25, gas: 20, metals: 15, rareEarth: 0, food: 60, water: 75 },
      stability: 68,
      approval: 38,
      techLevel: 8,
      diplomaticInfluence: 75,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 6. France
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'FR',
    name: 'France',
    capital: 'Paris',
    region: 'Europe',
    subregion: 'Western Europe',
    latitude: 48.8566,
    longitude: 2.3522,
    area: 643801,
    population: 67750000,
    flag: '🇫🇷',
    startingState: {
      code: 'FR',
      economy: {
        gdp: 2780,
        gdpGrowth: 1.1,
        budget: 32,
        taxRate: 0.30,
        tradeBalance: -110,
        debtToGdp: 1.12,
        inflation: 5.2,
        sanctionResilience: 60,
        sanctionEvasion: 15,
      },
      military: {
        army: 205000,
        navy: 120,
        airForce: 1050,
        nuclearWeapons: 290,
        defenseBudget: 56,
        techLevel: 8,
      },
      resources: { oil: 5, gas: 5, metals: 20, rareEarth: 2, food: 85, water: 80 },
      stability: 55,
      approval: 35,
      techLevel: 8,
      diplomaticInfluence: 70,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 7. Germany
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'DE',
    name: 'Germany',
    capital: 'Berlin',
    region: 'Europe',
    subregion: 'Western Europe',
    latitude: 52.52,
    longitude: 13.405,
    area: 357114,
    population: 83200000,
    flag: '🇩🇪',
    startingState: {
      code: 'DE',
      economy: {
        gdp: 4070,
        gdpGrowth: 0.2,
        budget: 45,
        taxRate: 0.30,
        tradeBalance: 180,
        debtToGdp: 0.66,
        inflation: 6.0,
        sanctionResilience: 55,
        sanctionEvasion: 10,
      },
      military: {
        army: 183000,
        navy: 60,
        airForce: 620,
        nuclearWeapons: 0,
        defenseBudget: 56,
        techLevel: 8,
      },
      resources: { oil: 5, gas: 5, metals: 30, rareEarth: 2, food: 75, water: 80 },
      stability: 70,
      approval: 42,
      techLevel: 8,
      diplomaticInfluence: 72,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 8. Japan
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'JP',
    name: 'Japan',
    capital: 'Tokyo',
    region: 'Asia',
    subregion: 'Eastern Asia',
    latitude: 35.6762,
    longitude: 139.6503,
    area: 377975,
    population: 125700000,
    flag: '🇯🇵',
    startingState: {
      code: 'JP',
      economy: {
        gdp: 4230,
        gdpGrowth: 1.0,
        budget: 38,
        taxRate: 0.23,
        tradeBalance: -70,
        debtToGdp: 2.55,
        inflation: 3.3,
        sanctionResilience: 60,
        sanctionEvasion: 15,
      },
      military: {
        army: 247000,
        navy: 155,
        airForce: 740,
        nuclearWeapons: 0,
        defenseBudget: 47,
        techLevel: 9,
      },
      resources: { oil: 2, gas: 5, metals: 10, rareEarth: 0, food: 40, water: 70 },
      stability: 78,
      approval: 48,
      techLevel: 9,
      diplomaticInfluence: 60,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 9. Brazil
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'BR',
    name: 'Brazil',
    capital: 'Brasilia',
    region: 'South America',
    subregion: 'South America',
    latitude: -15.7975,
    longitude: -47.8919,
    area: 8515767,
    population: 214300000,
    flag: '🇧🇷',
    startingState: {
      code: 'BR',
      economy: {
        gdp: 1920,
        gdpGrowth: 2.9,
        budget: 15,
        taxRate: 0.22,
        tradeBalance: 45,
        debtToGdp: 0.73,
        inflation: 5.8,
        sanctionResilience: 70,
        sanctionEvasion: 35,
      },
      military: {
        army: 366000,
        navy: 95,
        airForce: 700,
        nuclearWeapons: 0,
        defenseBudget: 20,
        techLevel: 4,
      },
      resources: { oil: 50, gas: 20, metals: 75, rareEarth: 18, food: 95, water: 95 },
      stability: 52,
      approval: 40,
      techLevel: 5,
      diplomaticInfluence: 40,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 10. South Korea
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'KR',
    name: 'South Korea',
    capital: 'Seoul',
    region: 'Asia',
    subregion: 'Eastern Asia',
    latitude: 37.5665,
    longitude: 126.978,
    area: 100210,
    population: 51740000,
    flag: '🇰🇷',
    startingState: {
      code: 'KR',
      economy: {
        gdp: 1665,
        gdpGrowth: 2.6,
        budget: 28,
        taxRate: 0.22,
        tradeBalance: 30,
        debtToGdp: 0.54,
        inflation: 3.6,
        sanctionResilience: 55,
        sanctionEvasion: 20,
      },
      military: {
        army: 555000,
        navy: 90,
        airForce: 620,
        nuclearWeapons: 0,
        defenseBudget: 46,
        techLevel: 8,
      },
      resources: { oil: 0, gas: 0, metals: 15, rareEarth: 0, food: 35, water: 60 },
      stability: 72,
      approval: 50,
      techLevel: 8,
      diplomaticInfluence: 42,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 11. Australia
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'AU',
    name: 'Australia',
    capital: 'Canberra',
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    latitude: -35.2809,
    longitude: 149.13,
    area: 7692024,
    population: 25900000,
    flag: '🇦🇺',
    startingState: {
      code: 'AU',
      economy: {
        gdp: 1680,
        gdpGrowth: 3.6,
        budget: 25,
        taxRate: 0.24,
        tradeBalance: 90,
        debtToGdp: 0.56,
        inflation: 6.6,
        sanctionResilience: 65,
        sanctionEvasion: 15,
      },
      military: {
        army: 59000,
        navy: 48,
        airForce: 260,
        nuclearWeapons: 0,
        defenseBudget: 32,
        techLevel: 7,
      },
      resources: { oil: 20, gas: 55, metals: 90, rareEarth: 12, food: 80, water: 40 },
      stability: 80,
      approval: 52,
      techLevel: 7,
      diplomaticInfluence: 45,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 12. Canada
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'CA',
    name: 'Canada',
    capital: 'Ottawa',
    region: 'North America',
    subregion: 'Northern America',
    latitude: 45.4215,
    longitude: -75.6972,
    area: 9984670,
    population: 38930000,
    flag: '🇨🇦',
    startingState: {
      code: 'CA',
      economy: {
        gdp: 2140,
        gdpGrowth: 1.5,
        budget: 28,
        taxRate: 0.26,
        tradeBalance: -20,
        debtToGdp: 1.07,
        inflation: 3.9,
        sanctionResilience: 65,
        sanctionEvasion: 15,
      },
      military: {
        army: 68000,
        navy: 34,
        airForce: 390,
        nuclearWeapons: 0,
        defenseBudget: 27,
        techLevel: 7,
      },
      resources: { oil: 80, gas: 70, metals: 65, rareEarth: 8, food: 85, water: 95 },
      stability: 78,
      approval: 48,
      techLevel: 7,
      diplomaticInfluence: 48,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 13. Italy
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'IT',
    name: 'Italy',
    capital: 'Rome',
    region: 'Europe',
    subregion: 'Southern Europe',
    latitude: 41.9028,
    longitude: 12.4964,
    area: 301340,
    population: 59110000,
    flag: '🇮🇹',
    startingState: {
      code: 'IT',
      economy: {
        gdp: 2010,
        gdpGrowth: 0.7,
        budget: 22,
        taxRate: 0.28,
        tradeBalance: 35,
        debtToGdp: 1.44,
        inflation: 5.9,
        sanctionResilience: 50,
        sanctionEvasion: 20,
      },
      military: {
        army: 170000,
        navy: 65,
        airForce: 550,
        nuclearWeapons: 0,
        defenseBudget: 30,
        techLevel: 7,
      },
      resources: { oil: 5, gas: 8, metals: 15, rareEarth: 0, food: 70, water: 65 },
      stability: 58,
      approval: 35,
      techLevel: 7,
      diplomaticInfluence: 48,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 14. Saudi Arabia
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'SA',
    name: 'Saudi Arabia',
    capital: 'Riyadh',
    region: 'Asia',
    subregion: 'Western Asia',
    latitude: 24.7136,
    longitude: 46.6753,
    area: 2149690,
    population: 36000000,
    flag: '🇸🇦',
    startingState: {
      code: 'SA',
      economy: {
        gdp: 1108,
        gdpGrowth: 3.9,
        budget: 30,
        taxRate: 0.05,
        tradeBalance: 160,
        debtToGdp: 0.24,
        inflation: 2.5,
        sanctionResilience: 60,
        sanctionEvasion: 35,
      },
      military: {
        army: 227000,
        navy: 55,
        airForce: 340,
        nuclearWeapons: 0,
        defenseBudget: 75,
        techLevel: 6,
      },
      resources: { oil: 100, gas: 75, metals: 15, rareEarth: 5, food: 10, water: 5 },
      stability: 70,
      approval: 65,
      techLevel: 5,
      diplomaticInfluence: 55,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 15. Iran
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'IR',
    name: 'Iran',
    capital: 'Tehran',
    region: 'Asia',
    subregion: 'Western Asia',
    latitude: 35.6892,
    longitude: 51.389,
    area: 1648195,
    population: 87590000,
    flag: '🇮🇷',
    startingState: {
      code: 'IR',
      economy: {
        gdp: 388,
        gdpGrowth: 2.5,
        budget: 8,
        taxRate: 0.09,
        tradeBalance: 15,
        debtToGdp: 0.42,
        inflation: 42.0,
        sanctionResilience: 55,
        sanctionEvasion: 70,
      },
      military: {
        army: 610000,
        navy: 80,
        airForce: 340,
        nuclearWeapons: 0,
        defenseBudget: 25,
        techLevel: 4,
      },
      resources: { oil: 85, gas: 80, metals: 30, rareEarth: 5, food: 40, water: 25 },
      stability: 40,
      approval: 35,
      techLevel: 4,
      diplomaticInfluence: 30,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 16. Turkey
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'TR',
    name: 'Turkey',
    capital: 'Ankara',
    region: 'Asia',
    subregion: 'Western Asia',
    latitude: 39.9334,
    longitude: 32.8597,
    area: 783562,
    population: 85280000,
    flag: '🇹🇷',
    startingState: {
      code: 'TR',
      economy: {
        gdp: 905,
        gdpGrowth: 4.5,
        budget: 14,
        taxRate: 0.20,
        tradeBalance: -55,
        debtToGdp: 0.32,
        inflation: 65.0,
        sanctionResilience: 55,
        sanctionEvasion: 50,
      },
      military: {
        army: 425000,
        navy: 80,
        airForce: 550,
        nuclearWeapons: 0,
        defenseBudget: 18,
        techLevel: 6,
      },
      resources: { oil: 5, gas: 3, metals: 40, rareEarth: 5, food: 65, water: 50 },
      stability: 48,
      approval: 42,
      techLevel: 5,
      diplomaticInfluence: 42,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 17. Israel
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'IL',
    name: 'Israel',
    capital: 'Jerusalem',
    region: 'Asia',
    subregion: 'Western Asia',
    latitude: 31.7683,
    longitude: 35.2137,
    area: 22072,
    population: 9364000,
    flag: '🇮🇱',
    startingState: {
      code: 'IL',
      economy: {
        gdp: 525,
        gdpGrowth: 3.4,
        budget: 18,
        taxRate: 0.25,
        tradeBalance: -15,
        debtToGdp: 0.61,
        inflation: 4.3,
        sanctionResilience: 50,
        sanctionEvasion: 30,
      },
      military: {
        army: 170000,
        navy: 14,
        airForce: 580,
        nuclearWeapons: 90,
        defenseBudget: 24,
        techLevel: 9,
      },
      resources: { oil: 2, gas: 30, metals: 5, rareEarth: 0, food: 35, water: 15 },
      stability: 55,
      approval: 50,
      techLevel: 9,
      diplomaticInfluence: 45,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 18. Ukraine
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'UA',
    name: 'Ukraine',
    capital: 'Kyiv',
    region: 'Europe',
    subregion: 'Eastern Europe',
    latitude: 50.4501,
    longitude: 30.5234,
    area: 603550,
    population: 43790000,
    flag: '🇺🇦',
    startingState: {
      code: 'UA',
      economy: {
        gdp: 160,
        gdpGrowth: -29.1,
        budget: 3,
        taxRate: 0.18,
        tradeBalance: -25,
        debtToGdp: 0.78,
        inflation: 20.0,
        sanctionResilience: 35,
        sanctionEvasion: 25,
      },
      military: {
        army: 900000,
        navy: 5,
        airForce: 120,
        nuclearWeapons: 0,
        defenseBudget: 44,
        techLevel: 5,
      },
      resources: { oil: 10, gas: 15, metals: 45, rareEarth: 5, food: 80, water: 70 },
      stability: 35,
      approval: 75,
      techLevel: 4,
      diplomaticInfluence: 38,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 19. Pakistan
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'PK',
    name: 'Pakistan',
    capital: 'Islamabad',
    region: 'Asia',
    subregion: 'Southern Asia',
    latitude: 33.6844,
    longitude: 73.0479,
    area: 881913,
    population: 231400000,
    flag: '🇵🇰',
    startingState: {
      code: 'PK',
      economy: {
        gdp: 376,
        gdpGrowth: 2.0,
        budget: 5,
        taxRate: 0.12,
        tradeBalance: -35,
        debtToGdp: 0.75,
        inflation: 28.0,
        sanctionResilience: 40,
        sanctionEvasion: 35,
      },
      military: {
        army: 654000,
        navy: 36,
        airForce: 430,
        nuclearWeapons: 165,
        defenseBudget: 10,
        techLevel: 4,
      },
      resources: { oil: 8, gas: 20, metals: 25, rareEarth: 5, food: 55, water: 35 },
      stability: 38,
      approval: 32,
      techLevel: 3,
      diplomaticInfluence: 25,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 20. Egypt
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'EG',
    name: 'Egypt',
    capital: 'Cairo',
    region: 'Africa',
    subregion: 'Northern Africa',
    latitude: 30.0444,
    longitude: 31.2357,
    area: 1002450,
    population: 104260000,
    flag: '🇪🇬',
    startingState: {
      code: 'EG',
      economy: {
        gdp: 404,
        gdpGrowth: 3.3,
        budget: 6,
        taxRate: 0.14,
        tradeBalance: -40,
        debtToGdp: 0.87,
        inflation: 15.0,
        sanctionResilience: 45,
        sanctionEvasion: 30,
      },
      military: {
        army: 450000,
        navy: 60,
        airForce: 580,
        nuclearWeapons: 0,
        defenseBudget: 7,
        techLevel: 4,
      },
      resources: { oil: 25, gas: 40, metals: 15, rareEarth: 2, food: 30, water: 10 },
      stability: 50,
      approval: 45,
      techLevel: 3,
      diplomaticInfluence: 32,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 21. Nigeria
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'NG',
    name: 'Nigeria',
    capital: 'Abuja',
    region: 'Africa',
    subregion: 'Western Africa',
    latitude: 9.0765,
    longitude: 7.3986,
    area: 923768,
    population: 218500000,
    flag: '🇳🇬',
    startingState: {
      code: 'NG',
      economy: {
        gdp: 477,
        gdpGrowth: 3.0,
        budget: 4,
        taxRate: 0.08,
        tradeBalance: 5,
        debtToGdp: 0.38,
        inflation: 22.0,
        sanctionResilience: 50,
        sanctionEvasion: 40,
      },
      military: {
        army: 135000,
        navy: 18,
        airForce: 80,
        nuclearWeapons: 0,
        defenseBudget: 3,
        techLevel: 2,
      },
      resources: { oil: 70, gas: 55, metals: 30, rareEarth: 5, food: 50, water: 50 },
      stability: 35,
      approval: 30,
      techLevel: 2,
      diplomaticInfluence: 22,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 22. South Africa
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'ZA',
    name: 'South Africa',
    capital: 'Pretoria',
    region: 'Africa',
    subregion: 'Southern Africa',
    latitude: -25.7479,
    longitude: 28.2293,
    area: 1221037,
    population: 60140000,
    flag: '🇿🇦',
    startingState: {
      code: 'ZA',
      economy: {
        gdp: 405,
        gdpGrowth: 1.2,
        budget: 6,
        taxRate: 0.22,
        tradeBalance: 15,
        debtToGdp: 0.71,
        inflation: 6.9,
        sanctionResilience: 55,
        sanctionEvasion: 30,
      },
      military: {
        army: 73000,
        navy: 30,
        airForce: 210,
        nuclearWeapons: 0,
        defenseBudget: 3,
        techLevel: 3,
      },
      resources: { oil: 5, gas: 10, metals: 90, rareEarth: 3, food: 45, water: 30 },
      stability: 42,
      approval: 35,
      techLevel: 4,
      diplomaticInfluence: 28,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 23. Mexico
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'MX',
    name: 'Mexico',
    capital: 'Mexico City',
    region: 'North America',
    subregion: 'Central America',
    latitude: 19.4326,
    longitude: -99.1332,
    area: 1964375,
    population: 128900000,
    flag: '🇲🇽',
    startingState: {
      code: 'MX',
      economy: {
        gdp: 1322,
        gdpGrowth: 3.1,
        budget: 12,
        taxRate: 0.16,
        tradeBalance: -10,
        debtToGdp: 0.54,
        inflation: 7.9,
        sanctionResilience: 55,
        sanctionEvasion: 35,
      },
      military: {
        army: 277000,
        navy: 44,
        airForce: 380,
        nuclearWeapons: 0,
        defenseBudget: 8,
        techLevel: 4,
      },
      resources: { oil: 50, gas: 25, metals: 40, rareEarth: 3, food: 65, water: 45 },
      stability: 42,
      approval: 38,
      techLevel: 4,
      diplomaticInfluence: 30,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 24. Indonesia
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'ID',
    name: 'Indonesia',
    capital: 'Jakarta',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    latitude: -6.2088,
    longitude: 106.8456,
    area: 1904569,
    population: 275500000,
    flag: '🇮🇩',
    startingState: {
      code: 'ID',
      economy: {
        gdp: 1319,
        gdpGrowth: 5.3,
        budget: 10,
        taxRate: 0.12,
        tradeBalance: 35,
        debtToGdp: 0.39,
        inflation: 4.2,
        sanctionResilience: 65,
        sanctionEvasion: 30,
      },
      military: {
        army: 400000,
        navy: 65,
        airForce: 450,
        nuclearWeapons: 0,
        defenseBudget: 9,
        techLevel: 3,
      },
      resources: { oil: 35, gas: 50, metals: 60, rareEarth: 8, food: 70, water: 80 },
      stability: 60,
      approval: 55,
      techLevel: 3,
      diplomaticInfluence: 28,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 25. Thailand
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'TH',
    name: 'Thailand',
    capital: 'Bangkok',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    latitude: 13.7563,
    longitude: 100.5018,
    area: 513120,
    population: 71800000,
    flag: '🇹🇭',
    startingState: {
      code: 'TH',
      economy: {
        gdp: 536,
        gdpGrowth: 2.6,
        budget: 8,
        taxRate: 0.15,
        tradeBalance: 20,
        debtToGdp: 0.61,
        inflation: 2.2,
        sanctionResilience: 55,
        sanctionEvasion: 30,
      },
      military: {
        army: 361000,
        navy: 48,
        airForce: 380,
        nuclearWeapons: 0,
        defenseBudget: 7,
        techLevel: 4,
      },
      resources: { oil: 10, gas: 20, metals: 20, rareEarth: 2, food: 85, water: 75 },
      stability: 55,
      approval: 45,
      techLevel: 4,
      diplomaticInfluence: 22,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 26. Poland
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'PL',
    name: 'Poland',
    capital: 'Warsaw',
    region: 'Europe',
    subregion: 'Central Europe',
    latitude: 52.2297,
    longitude: 21.0122,
    area: 312696,
    population: 37750000,
    flag: '🇵🇱',
    startingState: {
      code: 'PL',
      economy: {
        gdp: 700,
        gdpGrowth: 3.4,
        budget: 12,
        taxRate: 0.22,
        tradeBalance: -10,
        debtToGdp: 0.49,
        inflation: 11.4,
        sanctionResilience: 45,
        sanctionEvasion: 15,
      },
      military: {
        army: 150000,
        navy: 24,
        airForce: 310,
        nuclearWeapons: 0,
        defenseBudget: 16,
        techLevel: 5,
      },
      resources: { oil: 3, gas: 8, metals: 30, rareEarth: 2, food: 70, water: 65 },
      stability: 65,
      approval: 45,
      techLevel: 5,
      diplomaticInfluence: 30,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 27. Argentina
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'AR',
    name: 'Argentina',
    capital: 'Buenos Aires',
    region: 'South America',
    subregion: 'South America',
    latitude: -34.6037,
    longitude: -58.3816,
    area: 2780400,
    population: 45810000,
    flag: '🇦🇷',
    startingState: {
      code: 'AR',
      economy: {
        gdp: 641,
        gdpGrowth: 1.0,
        budget: 7,
        taxRate: 0.20,
        tradeBalance: 10,
        debtToGdp: 0.80,
        inflation: 95.0,
        sanctionResilience: 50,
        sanctionEvasion: 40,
      },
      military: {
        army: 80000,
        navy: 30,
        airForce: 200,
        nuclearWeapons: 0,
        defenseBudget: 3,
        techLevel: 3,
      },
      resources: { oil: 30, gas: 40, metals: 35, rareEarth: 5, food: 90, water: 80 },
      stability: 38,
      approval: 35,
      techLevel: 4,
      diplomaticInfluence: 22,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 28. Spain
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'ES',
    name: 'Spain',
    capital: 'Madrid',
    region: 'Europe',
    subregion: 'Southern Europe',
    latitude: 40.4168,
    longitude: -3.7038,
    area: 505990,
    population: 47420000,
    flag: '🇪🇸',
    startingState: {
      code: 'ES',
      economy: {
        gdp: 1398,
        gdpGrowth: 2.5,
        budget: 18,
        taxRate: 0.25,
        tradeBalance: -35,
        debtToGdp: 1.13,
        inflation: 3.5,
        sanctionResilience: 50,
        sanctionEvasion: 15,
      },
      military: {
        army: 123000,
        navy: 45,
        airForce: 380,
        nuclearWeapons: 0,
        defenseBudget: 15,
        techLevel: 6,
      },
      resources: { oil: 3, gas: 2, metals: 20, rareEarth: 2, food: 70, water: 45 },
      stability: 62,
      approval: 40,
      techLevel: 6,
      diplomaticInfluence: 38,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 29. Sweden
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'SE',
    name: 'Sweden',
    capital: 'Stockholm',
    region: 'Europe',
    subregion: 'Northern Europe',
    latitude: 59.3293,
    longitude: 18.0686,
    area: 450295,
    population: 10420000,
    flag: '🇸🇪',
    startingState: {
      code: 'SE',
      economy: {
        gdp: 586,
        gdpGrowth: 1.1,
        budget: 14,
        taxRate: 0.33,
        tradeBalance: 30,
        debtToGdp: 0.33,
        inflation: 6.8,
        sanctionResilience: 55,
        sanctionEvasion: 10,
      },
      military: {
        army: 24000,
        navy: 18,
        airForce: 130,
        nuclearWeapons: 0,
        defenseBudget: 8,
        techLevel: 7,
      },
      resources: { oil: 0, gas: 0, metals: 60, rareEarth: 15, food: 50, water: 90 },
      stability: 82,
      approval: 55,
      techLevel: 8,
      diplomaticInfluence: 38,
      indexOfPower: 0,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 30. North Korea
  // ─────────────────────────────────────────────────────────────────────────────
  {
    code: 'KP',
    name: 'North Korea',
    capital: 'Pyongyang',
    region: 'Asia',
    subregion: 'Eastern Asia',
    latitude: 39.0392,
    longitude: 125.7625,
    area: 120538,
    population: 25970000,
    flag: '🇰🇵',
    startingState: {
      code: 'KP',
      economy: {
        gdp: 18,
        gdpGrowth: -0.1,
        budget: 2,
        taxRate: 0.0,
        tradeBalance: -2,
        debtToGdp: 0.0,
        inflation: 5.0,
        sanctionResilience: 80,
        sanctionEvasion: 75,
      },
      military: {
        army: 1280000,
        navy: 70,
        airForce: 940,
        nuclearWeapons: 50,
        defenseBudget: 4,
        techLevel: 3,
      },
      resources: { oil: 0, gas: 0, metals: 45, rareEarth: 15, food: 20, water: 50 },
      stability: 85,
      approval: 100,
      techLevel: 2,
      diplomaticInfluence: 8,
      indexOfPower: 0,
    },
  },
];
