// ISO 3166-1 numeric → { ISO_A2, name } mapping for countries-110m.json
// Only includes the 30 game countries + major others for polygon labels
export const NUMERIC_TO_COUNTRY: Record<string, { code: string; name: string }> = {
  '840': { code: 'US', name: 'United States' },
  '156': { code: 'CN', name: 'China' },
  '643': { code: 'RU', name: 'Russia' },
  '356': { code: 'IN', name: 'India' },
  '826': { code: 'GB', name: 'United Kingdom' },
  '250': { code: 'FR', name: 'France' },
  '276': { code: 'DE', name: 'Germany' },
  '392': { code: 'JP', name: 'Japan' },
  '076': { code: 'BR', name: 'Brazil' },
  '410': { code: 'KR', name: 'South Korea' },
  '036': { code: 'AU', name: 'Australia' },
  '124': { code: 'CA', name: 'Canada' },
  '380': { code: 'IT', name: 'Italy' },
  '682': { code: 'SA', name: 'Saudi Arabia' },
  '364': { code: 'IR', name: 'Iran' },
  '792': { code: 'TR', name: 'Turkey' },
  '376': { code: 'IL', name: 'Israel' },
  '804': { code: 'UA', name: 'Ukraine' },
  '586': { code: 'PK', name: 'Pakistan' },
  '818': { code: 'EG', name: 'Egypt' },
  '566': { code: 'NG', name: 'Nigeria' },
  '710': { code: 'ZA', name: 'South Africa' },
  '484': { code: 'MX', name: 'Mexico' },
  '360': { code: 'ID', name: 'Indonesia' },
  '764': { code: 'TH', name: 'Thailand' },
  '616': { code: 'PL', name: 'Poland' },
  '032': { code: 'AR', name: 'Argentina' },
  '724': { code: 'ES', name: 'Spain' },
  '752': { code: 'SE', name: 'Sweden' },
  '408': { code: 'KP', name: 'North Korea' },
  // Additional major countries for better labels
  '004': { code: 'AF', name: 'Afghanistan' },
  '012': { code: 'DZ', name: 'Algeria' },
  '024': { code: 'AO', name: 'Angola' },
  '040': { code: 'AT', name: 'Austria' },
  '050': { code: 'BD', name: 'Bangladesh' },
  '056': { code: 'BE', name: 'Belgium' },
  '064': { code: 'BT', name: 'Bhutan' },
  '068': { code: 'BO', name: 'Bolivia' },
  '100': { code: 'BG', name: 'Bulgaria' },
  '104': { code: 'MM', name: 'Myanmar' },
  '116': { code: 'KH', name: 'Cambodia' },
  '120': { code: 'CM', name: 'Cameroon' },
  '144': { code: 'LK', name: 'Sri Lanka' },
  '148': { code: 'TD', name: 'Chad' },
  '152': { code: 'CL', name: 'Chile' },
  '170': { code: 'CO', name: 'Colombia' },
  '178': { code: 'CG', name: 'Congo' },
  '180': { code: 'CD', name: 'DR Congo' },
  '188': { code: 'CR', name: 'Costa Rica' },
  '192': { code: 'CU', name: 'Cuba' },
  '196': { code: 'CY', name: 'Cyprus' },
  '203': { code: 'CZ', name: 'Czech Republic' },
  '208': { code: 'DK', name: 'Denmark' },
  '218': { code: 'EC', name: 'Ecuador' },
  '231': { code: 'ET', name: 'Ethiopia' },
  '233': { code: 'EE', name: 'Estonia' },
  '246': { code: 'FI', name: 'Finland' },
  '268': { code: 'GE', name: 'Georgia' },
  '288': { code: 'GH', name: 'Ghana' },
  '300': { code: 'GR', name: 'Greece' },
  '320': { code: 'GT', name: 'Guatemala' },
  '332': { code: 'HT', name: 'Haiti' },
  '340': { code: 'HN', name: 'Honduras' },
  '348': { code: 'HU', name: 'Hungary' },
  '352': { code: 'IS', name: 'Iceland' },
  '368': { code: 'IQ', name: 'Iraq' },
  '372': { code: 'IE', name: 'Ireland' },
  '398': { code: 'KZ', name: 'Kazakhstan' },
  '404': { code: 'KE', name: 'Kenya' },
  '414': { code: 'KW', name: 'Kuwait' },
  '418': { code: 'LA', name: 'Laos' },
  '422': { code: 'LB', name: 'Lebanon' },
  '434': { code: 'LY', name: 'Libya' },
  '440': { code: 'LT', name: 'Lithuania' },
  '458': { code: 'MY', name: 'Malaysia' },
  '466': { code: 'ML', name: 'Mali' },
  '496': { code: 'MN', name: 'Mongolia' },
  '504': { code: 'MA', name: 'Morocco' },
  '508': { code: 'MZ', name: 'Mozambique' },
  '516': { code: 'NA', name: 'Namibia' },
  '524': { code: 'NP', name: 'Nepal' },
  '528': { code: 'NL', name: 'Netherlands' },
  '554': { code: 'NZ', name: 'New Zealand' },
  '558': { code: 'NI', name: 'Nicaragua' },
  '562': { code: 'NE', name: 'Niger' },
  '578': { code: 'NO', name: 'Norway' },
  '512': { code: 'OM', name: 'Oman' },
  '591': { code: 'PA', name: 'Panama' },
  '598': { code: 'PG', name: 'Papua New Guinea' },
  '600': { code: 'PY', name: 'Paraguay' },
  '604': { code: 'PE', name: 'Peru' },
  '608': { code: 'PH', name: 'Philippines' },
  '620': { code: 'PT', name: 'Portugal' },
  '634': { code: 'QA', name: 'Qatar' },
  '642': { code: 'RO', name: 'Romania' },
  '646': { code: 'RW', name: 'Rwanda' },
  '686': { code: 'SN', name: 'Senegal' },
  '688': { code: 'RS', name: 'Serbia' },
  '694': { code: 'SL', name: 'Sierra Leone' },
  '702': { code: 'SG', name: 'Singapore' },
  '703': { code: 'SK', name: 'Slovakia' },
  '706': { code: 'SO', name: 'Somalia' },
  '728': { code: 'SS', name: 'South Sudan' },
  '729': { code: 'SD', name: 'Sudan' },
  '756': { code: 'CH', name: 'Switzerland' },
  '760': { code: 'SY', name: 'Syria' },
  '762': { code: 'TJ', name: 'Tajikistan' },
  '834': { code: 'TZ', name: 'Tanzania' },
  '788': { code: 'TN', name: 'Tunisia' },
  '795': { code: 'TM', name: 'Turkmenistan' },
  '800': { code: 'UG', name: 'Uganda' },
  '784': { code: 'AE', name: 'UAE' },
  '858': { code: 'UY', name: 'Uruguay' },
  '860': { code: 'UZ', name: 'Uzbekistan' },
  '862': { code: 'VE', name: 'Venezuela' },
  '704': { code: 'VN', name: 'Vietnam' },
  '887': { code: 'YE', name: 'Yemen' },
  '894': { code: 'ZM', name: 'Zambia' },
  '716': { code: 'ZW', name: 'Zimbabwe' },
};
